from enum import StrEnum


class MessageType(StrEnum):
    # League Manager Messages
    ROUND_ANNOUNCEMENT = "ROUND_ANNOUNCEMENT"
    ROUND_COMPLETED = "ROUND_COMPLETED"
    LEAGUE_STANDINGS_UPDATE = "LEAGUE_STANDINGS_UPDATE"
    LEAGUE_COMPLETED = "LEAGUE_COMPLETED"
    LEAGUE_QUERY_RESPONSE = "LEAGUE_QUERY_RESPONSE"
    LEAGUE_ERROR = "LEAGUE_ERROR"
    LEAGUE_REGISTER_RESPONSE = "LEAGUE_REGISTER_RESPONSE"
    MATCH_RESULT_ACK = "MATCH_RESULT_ACK"
    LEAGUE_STATUS = "LEAGUE_STATUS"

    # Referee Messages
    REFEREE_REGISTER_REQUEST = "REFEREE_REGISTER_REQUEST"
    REFEREE_REGISTER_RESPONSE = "REFEREE_REGISTER_RESPONSE"
    GAME_INVITATION = "GAME_INVITATION"
    CHOOSE_PARITY_CALL = "CHOOSE_PARITY_CALL"
    GAME_OVER = "GAME_OVER"
    MATCH_RESULT_REPORT = "MATCH_RESULT_REPORT"
    GAME_ERROR = "GAME_ERROR"

    # Player Messages
    LEAGUE_REGISTER_REQUEST = "LEAGUE_REGISTER_REQUEST"
    GAME_JOIN_ACK = "GAME_JOIN_ACK"
    CHOOSE_PARITY_RESPONSE = "CHOOSE_PARITY_RESPONSE"
    LEAGUE_QUERY = "LEAGUE_QUERY"

    # Launcher Messages
    START_LEAGUE = "START_LEAGUE"


class GameType(StrEnum):
    EVEN_ODD = "even_odd"


class ProtocolVersion(StrEnum):
    V2 = "league.v2"


class GameResultStatus(StrEnum):
    WIN = "WIN"
    DRAW = "DRAW"
    TECHNICAL_LOSS = "TECHNICAL_LOSS"


class ErrorCode(StrEnum):
    TIMEOUT_ERROR = "E001"
    MISSING_REQUIRED_FIELD = "E003"
    INVALID_PARITY_CHOICE = "E004"
    PLAYER_NOT_REGISTERED = "E005"
    CONNECTION_ERROR = "E009"
    AUTH_TOKEN_MISSING = "E011"
    AUTH_TOKEN_INVALID = "E012"
    INVALID_TIMESTAMP = "E021"
